In [96]:
import pandas as pd 
import numpy as np 
from  sklearn.model_selection import train_test_split
from  sklearn.linear_model import LinearRegression

In [97]:
df=pd.read_csv("Cardetails.csv")

In [98]:
df.head()

                           name  year  selling_price  km_driven  ...   engine   max_power                    torque seats
0        Maruti Swift Dzire VDI  2014         450000     145500  ...  1248 CC      74 bhp            190Nm@ 2000rpm   5.0
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  ...  1498 CC  103.52 bhp       250Nm@ 1500-2500rpm   5.0
2      Honda City 2017-2020 EXi  2006         158000     140000  ...  1497 CC      78 bhp     12.7@ 2,700(kgm@ rpm)   5.0
3     Hyundai i20 Sportz Diesel  2010         225000     127000  ...  1396 CC      90 bhp  22.4 kgm at 1750-2750rpm   5.0
4        Maruti Swift VXI BSIII  2007         130000     120000  ...  1298 CC    88.2 bhp     11.5@ 4,500(kgm@ rpm)   5.0

[5 rows x 13 columns]

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           8128 non-null   object
 1   year           8128 non-null   int64
 2   selling_price  8128 non-null   int64
 3   km_driven      8128 non-null   int64
 4   fuel           8128 non-null   object
 5   seller_type    8128 non-null   object
 6   transmission   8128 non-null   object
 7   owner          8128 non-null   object
 8   mileage        7907 non-null   object
 9   engine         7907 non-null   object
 10  max_power      7913 non-null   object
 11  torque         7906 non-null   object
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB

In [100]:
df.shape

(8128, 13)

In [101]:
df.drop(columns=['torque'],inplace=True)

In [102]:
df.head()

                           name  year  selling_price  km_driven  ...     mileage   engine   max_power seats
0        Maruti Swift Dzire VDI  2014         450000     145500  ...   23.4 kmpl  1248 CC      74 bhp   5.0
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  ...  21.14 kmpl  1498 CC  103.52 bhp   5.0
2      Honda City 2017-2020 EXi  2006         158000     140000  ...   17.7 kmpl  1497 CC      78 bhp   5.0
3     Hyundai i20 Sportz Diesel  2010         225000     127000  ...   23.0 kmpl  1396 CC      90 bhp   5.0
4        Maruti Swift VXI BSIII  2007         130000     120000  ...   16.1 kmpl  1298 CC    88.2 bhp   5.0

[5 rows x 12 columns]

In [103]:
df.shape

(8128, 12)

In [104]:
df.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
seats            221
dtype: int64

In [105]:
df.dropna(inplace=True)

In [106]:
df.shape

(7907, 12)

In [107]:
df.duplicated().sum()

np.int64(1189)

In [108]:
df.drop_duplicates(inplace=True)

In [109]:
df.shape

(6718, 12)

In [110]:
df

                                   name  year  selling_price  km_driven  ...     mileage   engine   max_power seats
0                Maruti Swift Dzire VDI  2014         450000     145500  ...   23.4 kmpl  1248 CC      74 bhp   5.0
1          Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  ...  21.14 kmpl  1498 CC  103.52 bhp   5.0
2              Honda City 2017-2020 EXi  2006         158000     140000  ...   17.7 kmpl  1497 CC      78 bhp   5.0
3             Hyundai i20 Sportz Diesel  2010         225000     127000  ...   23.0 kmpl  1396 CC      90 bhp   5.0
4                Maruti Swift VXI BSIII  2007         130000     120000  ...   16.1 kmpl  1298 CC    88.2 bhp   5.0
...                                 ...   ...            ...        ...  ...         ...      ...         ...   ...
8121  Maruti Wagon R VXI BS IV with ABS  2013         260000      50000  ...   18.9 kmpl   998 CC    67.1 bhp   5.0
8122         Hyundai i20 Magna 1.4 CRDi  2014         475000      80000  ...  22.54 kmpl  1396 CC   88.73 bhp   5.0
8123                  Hyundai i20 Magna  2013         320000     110000  ...   18.5 kmpl  1197 CC   82.85 bhp   5.0
8124              Hyundai Verna CRDi SX  2007         135000     119000  ...   16.8 kmpl  1493 CC     110 bhp   5.0
8125             Maruti Swift Dzire ZDi  2009         382000     120000  ...   19.3 kmpl  1248 CC    73.9 bhp   5.0

[6718 rows x 12 columns]

In [111]:
df.columns.unique()

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage', 'engine', 'max_power', 'seats'],
      dtype='object')

In [112]:
for col in df.columns:
    print("Unique column is " +col)
    print(df[col].unique)
    print("-------------------")

Unique column is name
<bound method Series.unique of 0                  Maruti Swift Dzire VDI
1            Skoda Rapid 1.5 TDI Ambition
2                Honda City 2017-2020 EXi
3               Hyundai i20 Sportz Diesel
4                  Maruti Swift VXI BSIII
                      ...
8121    Maruti Wagon R VXI BS IV with ABS
8122           Hyundai i20 Magna 1.4 CRDi
8123                    Hyundai i20 Magna
8124                Hyundai Verna CRDi SX
8125               Maruti Swift Dzire ZDi
Name: name, Length: 6718, dtype: object>
-------------------
Unique column is year
<bound method Series.unique of 0       2014
1       2014
2       2006
3       2010
4       2007
        ...
8121    2013
8122    2014
8123    2013
8124    2007
8125    2009
Name: year, Length: 6718, dtype: int64>
-------------------
Unique column is selling_price
<bound method Series.unique of 0       450000
1       370000
2       158000
3       225000
4       130000
         ...
8121    260000
8122    475000
8123    320000
8124    135000
8125    382000
Name: selling_price, Length: 6718, dtype: int64>
-------------------
Unique column is km_driven
<bound method Series.unique of 0       145500
1       120000
2       140000
3       127000
4       120000
         ...
8121     50000
8122     80000
8123    110000
8124    119000
8125    120000
Name: km_driven, Length: 6718, dtype: int64>
-------------------
Unique column is fuel
<bound method Series.unique of 0       Diesel
1       Diesel
2       Petrol
3       Diesel
4       Petrol
         ...
8121    Petrol
8122    Diesel
8123    Petrol
8124    Diesel
8125    Diesel
Name: fuel, Length: 6718, dtype: object>
-------------------
Unique column is seller_type
<bound method Series.unique of 0       Individual
1       Individual
2       Individual
3       Individual
4       Individual
           ...
8121    Individual
8122    Individual
8123    Individual
8124    Individual
8125    Individual
Name: seller_type, Length: 6718, dtype: object>
-------------------
Unique column is transmission
<bound method Series.unique of 0       Manual
1       Manual
2       Manual
3       Manual
4       Manual
         ...
8121    Manual
8122    Manual
8123    Manual
8124    Manual
8125    Manual
Name: transmission, Length: 6718, dtype: object>
-------------------
Unique column is owner
<bound method Series.unique of 0                First Owner
1               Second Owner
2                Third Owner
3                First Owner
4                First Owner
                ...
8121            Second Owner
8122            Second Owner
8123             First Owner
8124    Fourth & Above Owner
8125             First Owner
Name: owner, Length: 6718, dtype: object>
-------------------
Unique column is mileage
<bound method Series.unique of 0        23.4 kmpl
1       21.14 kmpl
2        17.7 kmpl
3        23.0 kmpl
4        16.1 kmpl
           ...
8121     18.9 kmpl
8122    22.54 kmpl
8123     18.5 kmpl
8124     16.8 kmpl
8125     19.3 kmpl
Name: mileage, Length: 6718, dtype: object>
-------------------
Unique column is engine
<bound method Series.unique of 0       1248 CC
1       1498 CC
2       1497 CC
3       1396 CC
4       1298 CC
         ...
8121     998 CC
8122    1396 CC
8123    1197 CC
8124    1493 CC
8125    1248 CC
Name: engine, Length: 6718, dtype: object>
-------------------
Unique column is max_power
<bound method Series.unique of 0           74 bhp
1       103.52 bhp
2           78 bhp
3           90 bhp
4         88.2 bhp
           ...
8121      67.1 bhp
8122     88.73 bhp
8123     82.85 bhp
8124       110 bhp
8125      73.9 bhp
Name: max_power, Length: 6718, dtype: object>
-------------------
Unique column is seats
<bound method Series.unique of 0       5.0
1       5.0
2       5.0
3       5.0
4       5.0
       ...
8121    5.0
8122    5.0
8123    5.0
8124    5.0
8125    5.0
Name: seats, Length: 6718, dtype: float64>
-------------------

In [113]:
def get_brand_name(car_name):
    car_name=car_name.split(' ')[0]
    return car_name.strip()

In [114]:
def clean_data(value):
    value=value.split(' ')[0]
    value=value.strip()
    if value== '':
        value=0
    return float(value)

In [115]:
get_brand_name("maruti swift dezire")

'maruti'

In [116]:
df['name']=df['name'].apply(get_brand_name)

In [117]:
df['name'].unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Datsun', 'Jeep', 'Mercedes-Benz',
       'Mitsubishi', 'Audi', 'Volkswagen', 'BMW', 'Nissan', 'Lexus',
       'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo', 'Kia', 'Fiat', 'Force',
       'Ambassador', 'Ashok', 'Isuzu', 'Opel'], dtype=object)

In [118]:
df['mileage']=df['mileage'].apply(clean_data)

In [119]:
df['max_power']=df['max_power'].apply(clean_data)

In [120]:
df['engine']=df['engine'].apply(clean_data)

In [122]:
brand_mapping = {
    'Maruti': 1, 'Skoda': 2, 'Honda': 3, 'Hyundai': 4, 'Toyota': 5,
    'Ford': 6, 'Renault': 7, 'Mahindra': 8, 'Tata': 9, 'Chevrolet': 10,
    'Datsun': 11, 'Jeep': 12, 'Mercedes-Benz': 13, 'Mitsubishi': 14,
    'Audi': 15, 'Volkswagen': 16, 'BMW': 17, 'Nissan': 18, 'Lexus': 19,
    'Jaguar': 20, 'Land': 21, 'MG': 22, 'Volvo': 23, 'Daewoo': 24,
    'Kia': 25, 'Fiat': 26, 'Force': 27, 'Ambassador': 28, 'Ashok': 29,
    'Isuzu': 30, 'Opel': 31
}

df['name'] = df['name'].replace(brand_mapping)

In [123]:
df['transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [125]:
df['transmission'] = df['transmission'].replace({
    'Manual': 1,
    'Automatic': 2
})

In [126]:
df['seller_type'].unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [128]:
df['seller_type'] = df['seller_type'].replace({
    'Individual': 1,
    'Dealer': 2,
    'Trustmark Dealer': 3
})

In [129]:
df['fuel'].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [131]:
df['fuel']= df['fuel'].replace({
    'Diesel': 1,
    'Petrol': 2,
    'LPG': 3,
    'CNG': 4
})

In [132]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6718 entries, 0 to 8125
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6718 non-null   int64
 1   year           6718 non-null   int64
 2   selling_price  6718 non-null   int64
 3   km_driven      6718 non-null   int64
 4   fuel           6718 non-null   int64
 5   seller_type    6718 non-null   int64
 6   transmission   6718 non-null   int64
 7   owner          6718 non-null   object
 8   mileage        6718 non-null   float64
 9   engine         6718 non-null   float64
 10  max_power      6718 non-null   float64
 11  seats          6718 non-null   float64
dtypes: float64(4), int64(7), object(1)
memory usage: 682.3+ KB

In [133]:
df

      name  year  selling_price  km_driven  fuel  ...                 owner  mileage  engine  max_power  seats
0        1  2014         450000     145500     1  ...           First Owner    23.40  1248.0      74.00    5.0
1        2  2014         370000     120000     1  ...          Second Owner    21.14  1498.0     103.52    5.0
2        3  2006         158000     140000     2  ...           Third Owner    17.70  1497.0      78.00    5.0
3        4  2010         225000     127000     1  ...           First Owner    23.00  1396.0      90.00    5.0
4        1  2007         130000     120000     2  ...           First Owner    16.10  1298.0      88.20    5.0
...    ...   ...            ...        ...   ...  ...                   ...      ...     ...        ...    ...
8121     1  2013         260000      50000     2  ...          Second Owner    18.90   998.0      67.10    5.0
8122     4  2014         475000      80000     1  ...          Second Owner    22.54  1396.0      88.73    5.0
8123     4  2013         320000     110000     2  ...           First Owner    18.50  1197.0      82.85    5.0
8124     4  2007         135000     119000     1  ...  Fourth & Above Owner    16.80  1493.0     110.00    5.0
8125     1  2009         382000     120000     1  ...           First Owner    19.30  1248.0      73.90    5.0

[6718 rows x 12 columns]

In [134]:
df.reset_index(inplace=True)

In [135]:
df

      index  name  year  selling_price  km_driven  ...                 owner  mileage  engine max_power  seats
0         0     1  2014         450000     145500  ...           First Owner    23.40  1248.0     74.00    5.0
1         1     2  2014         370000     120000  ...          Second Owner    21.14  1498.0    103.52    5.0
2         2     3  2006         158000     140000  ...           Third Owner    17.70  1497.0     78.00    5.0
3         3     4  2010         225000     127000  ...           First Owner    23.00  1396.0     90.00    5.0
4         4     1  2007         130000     120000  ...           First Owner    16.10  1298.0     88.20    5.0
...     ...   ...   ...            ...        ...  ...                   ...      ...     ...       ...    ...
6713   8121     1  2013         260000      50000  ...          Second Owner    18.90   998.0     67.10    5.0
6714   8122     4  2014         475000      80000  ...          Second Owner    22.54  1396.0     88.73    5.0
6715   8123     4  2013         320000     110000  ...           First Owner    18.50  1197.0     82.85    5.0
6716   8124     4  2007         135000     119000  ...  Fourth & Above Owner    16.80  1493.0    110.00    5.0
6717   8125     1  2009         382000     120000  ...           First Owner    19.30  1248.0     73.90    5.0

[6718 rows x 13 columns]

In [136]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'], dtype=object)

In [138]:
df['owner']=   df['owner'].replace({
    'First Owner': 1,
    'Second Owner': 2,
    'Third Owner': 3,
    'Fourth & Above Owner': 4,
    'Test Drive Car':5
})

In [139]:
df

      index  name  year  selling_price  km_driven  fuel  ...  transmission  owner  mileage  engine  max_power  seats
0         0     1  2014         450000     145500     1  ...             1      1    23.40  1248.0      74.00    5.0
1         1     2  2014         370000     120000     1  ...             1      2    21.14  1498.0     103.52    5.0
2         2     3  2006         158000     140000     2  ...             1      3    17.70  1497.0      78.00    5.0
3         3     4  2010         225000     127000     1  ...             1      1    23.00  1396.0      90.00    5.0
4         4     1  2007         130000     120000     2  ...             1      1    16.10  1298.0      88.20    5.0
...     ...   ...   ...            ...        ...   ...  ...           ...    ...      ...     ...        ...    ...
6713   8121     1  2013         260000      50000     2  ...             1      2    18.90   998.0      67.10    5.0
6714   8122     4  2014         475000      80000     1  ...             1      2    22.54  1396.0      88.73    5.0
6715   8123     4  2013         320000     110000     2  ...             1      1    18.50  1197.0      82.85    5.0
6716   8124     4  2007         135000     119000     1  ...             1      4    16.80  1493.0     110.00    5.0
6717   8125     1  2009         382000     120000     1  ...             1      1    19.30  1248.0      73.90    5.0

[6718 rows x 13 columns]

In [140]:
df.drop(columns=['index'],inplace=True)

In [141]:
df

      name  year  selling_price  km_driven  fuel  seller_type  transmission  owner  mileage  engine  max_power  seats
0        1  2014         450000     145500     1            1             1      1    23.40  1248.0      74.00    5.0
1        2  2014         370000     120000     1            1             1      2    21.14  1498.0     103.52    5.0
2        3  2006         158000     140000     2            1             1      3    17.70  1497.0      78.00    5.0
3        4  2010         225000     127000     1            1             1      1    23.00  1396.0      90.00    5.0
4        1  2007         130000     120000     2            1             1      1    16.10  1298.0      88.20    5.0
...    ...   ...            ...        ...   ...          ...           ...    ...      ...     ...        ...    ...
6713     1  2013         260000      50000     2            1             1      2    18.90   998.0      67.10    5.0
6714     4  2014         475000      80000     1            1             1      2    22.54  1396.0      88.73    5.0
6715     4  2013         320000     110000     2            1             1      1    18.50  1197.0      82.85    5.0
6716     4  2007         135000     119000     1            1             1      4    16.80  1493.0     110.00    5.0
6717     1  2009         382000     120000     1            1             1      1    19.30  1248.0      73.90    5.0

[6718 rows x 12 columns]

In [142]:
X=df.drop(columns=['selling_price'])
y=df['selling_price']

In [143]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [144]:
model=LinearRegression()

In [145]:
model.fit(X_train,y_train)

LinearRegression()

In [146]:
y_pred=model.predict(X_test)

In [148]:
y_pred

array([175832.56326444, 975125.06604441, 346557.27883174, ...,
       529098.30392082, 277118.87014079, 557008.9216685 ])

In [152]:
df.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage', 'engine', 'max_power', 'seats'],
      dtype='object')

In [151]:
X_train.head(1)

      name  year  km_driven  fuel  seller_type  transmission  owner  mileage  engine  max_power  seats
5829     4  2014      15000     2            1             1      1    20.36  1197.0       78.9    5.0

In [160]:
input_data_model=pd.DataFrame(
    [[5	,2022	,12000,	1	,1,	1,	1	,12.99,	2494.0,	100.6,5.0]],
    columns=['name', 'year', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage', 'engine', 'max_power', 'seats']
)

In [161]:
input_data_model

   name  year  km_driven  fuel  seller_type  transmission  owner  mileage  engine  max_power  seats
0     5  2022      12000     1            1             1      1    12.99  2494.0      100.6    5.0

In [162]:
model.predict(input_data_model)

array([953324.22054859])

In [169]:
import pickle as pk

pk.dump(model, open("model.pkl", "wb"))